# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        # You may pin to the exact commit or the version.
        # uses: britannio/action-install-flutter@a486b7e3148e54a76390d849100b9dee819ff810
        uses: britannio/action-install-flutter@v1.1

      - name: Install dependencies
        run: flutter pub get

        
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: true
